// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TurkiyeBilgi.Models;

namespace TurkiyeBilgi.Migrations
{
    [DbContext(typeof(TurkiyeContext))]
    partial class TurkiyeContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.13")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TurkiyeBilgi.Models.Bolge", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("BolgeAd")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.HasKey("Id");

                    b.ToTable("Bolgeler");
                });

            modelBuilder.Entity("TurkiyeBilgi.Models.Sehir", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("BolgeId")
                        .HasColumnType("int");

                    b.Property<long>("Nufus")
                        .HasColumnType("bigint");

                    b.Property<string>("SehirAd")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.HasKey("Id");

                    b.HasIndex("BolgeId");

                    b.ToTable("Sehirler");
                });

            modelBuilder.Entity("TurkiyeBilgi.Models.Sehir", b =>
                {
                    b.HasOne("TurkiyeBilgi.Models.Bolge", "Bolge")
                        .WithMany("Sehirler")
                        .HasForeignKey("BolgeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bolge");
                });

            modelBuilder.Entity("TurkiyeBilgi.Models.Bolge", b =>
                {
                    b.Navigation("Sehirler");
                });
#pragma warning restore 612, 618
        }
    }
}
